name: stack-linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup packages
        run: |
          sudo bash -c "echo deb [trusted=yes] http://hasktorch.org/apt ./ > /etc/apt/sources.list.d/libtorch.list"
          sudo apt update -qq
          sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install cmake curl wget unzip git libtinfo-dev python3 python3-yaml
          sudo apt -y install libtorch=1.9.0+cpu-1 libtokenizers=0.1-1
          (wget -qO- https://get.haskellstack.org/ | sh) || true
      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: "\
            ${{ runner.os }}-stack\
            -${{ hashFiles('**/stack.yaml.lock') }}\
            -${{ hashFiles('**/package.yaml') }}\
          "
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: build
        run: |
          stack build
          stack install openmemex:exe:server
      - name: run
        run: |
          stack run server --help
