name: stack-linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup packages
        run: |
          sudo apt update -qq
          sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install cmake curl wget unzip git libtinfo-dev python3 python3-yaml
          (wget -qO- https://get.haskellstack.org/ | sh) || true
      - name: build
        run: |
          stack build
      - name: run
        run: |
          stack run n2s --help
